#
# seigo

remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

title                    : Sasaki Group
title_separator          : "-"
name                     : &name "Seigo Sasaki"
description              : Sasaki Group Web Page
url                      : https://sasaki-group.github.io

future: true

# Site Author
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  location         : "Yokosuka, Japan"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
