#
# seigo

remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

title                    : Sasaki Group
title_separator          : "-"
subtitle                 : "Automatic Control System Design"
name                     : &name "Seigo Sasaki"
description              : Sasaki Group Web Page
url                      : https://sasaki-group.github.io
words_per_minute         : 200

future: true

# Site Author
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  bio              : "University educator and researcher exploring the intersection of narrative and design thinking"
  location         : "Yokosuka, Japan"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/sasaki-group"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sasaki-group"
  # since: "2025"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      # comments: true
      share: true
      related: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
